# Generated by Django 3.1 on 2020-09-14 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 14, 22, 10, 24, 737203)),
        ),
    ]
