# Generated by Django 3.1 on 2020-09-14 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20200914_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 15, 1, 43, 16, 902155)),
        ),
    ]
